oneMKL: support axpy from level1
JuliaGPU/oneAPI.jl pull request #241
Opened 2022-11-08 10:56 UTC by kaliudayintel

This PR contains axpy primitive from level 1

2022-11-08 13:21 UTC, maleadt commented
Please *do not* open new PRs all the time; just make changes to your original PR's branch and push those.

2022-11-08 15:22 UTC, maleadt commented
Also, please reduce the number of commits. By pushing "NITS" commits that change nothing but whitespace, CI time is needlessly wasted.

2022-11-08 15:26 UTC, kaliudayintel commented
> Please do not open new PRs when there's an existing one; just make changes to your original PR's branch and push those.
> 
> Other than that, the CI failure here looks related, but happens during execution of `iamax`...

@maleadt  Thanks you. Sure, actually I happened to reopen a fresh PR as my local setup got corrupted after your merge of iamax during rebase/merge. I tried force pushing changes but that didnt work so raised a fresh PR to overcome it. Since this branch is created on top of my working version we have the history of CI runs here. I will ensure same PR maintained from next time.

2022-11-08 15:27 UTC, kaliudayintel commented
> Also, please reduce the number of commits. By pushing "NITS" commits that change nothing but whitespace, CI time is needlessly wasted.

Sure will follow the same. This time I wanted to trigger CI run once again and found NITS to enable it.

2022-11-08 15:29 UTC, maleadt commented
Thanks!

> my local setup got corrupted after your merge of iamax during rebase/merge. I tried force pushing changes but that didnt work so raised a fresh PR to overcome it

It requires a bit of git fu, but it's always possible to go to a new branch and then just push it to the old PR using `git push -u origin HEAD:your_previous_branch`.

2022-11-08 15:43 UTC, kaliudayintel commented
@maleadt I find that in local testing these tests are passing and also couple of previous CI runs are successful.
![image](https://user-images.githubusercontent.com/114738197/200609907-62718f4a-9d1f-4cb5-a534-99f40217501a.png)

2022-11-09 06:39 UTC, maleadt commented
> I find that in local testing these tests are passing

Then more effort is required to reproduce locally. Try running the operations in a loop instead of re-starting the test process, that should make it possible to quickly run a whole bunch of iterations.

2022-11-10 16:31 UTC, Sarbojit2019 requested changes

2022-11-10 16:31 UTC, Sarbojit2019 commented on deps/src/onemkl.cpp
> +                        reinterpret_cast<std::complex<double> *>(y), incy);
wait() is missing here.

2022-11-10 16:51 UTC, maleadt commented
> Then more effort is required to reproduce locally. 

For something more productive: try the approach from https://github.com/JuliaGPU/oneAPI.jl/issues/243, where you include the test in a while loop. That allows you to execute much more iterations much quicker, because it doesn't have to recompile over and over.

2022-11-10 16:55 UTC, kaliudayintel commented
> > Then more effort is required to reproduce locally.
> 
> For something more productive: try the approach from #243, where you include the test in a while loop. That allows you to execute much more iterations much quicker, because it doesn't have to recompile over and over.

@maleadt  Thanks for your suggestion. I have done this analysis and found that axpy fails locally in iterative runs. 
I will send a fix for the same soon.

2022-11-10 20:29 UTC, maleadt commented
Why does this `wait()`? It shouldn't, because that means these operations would synchronize the GPU. Instead, we only synchronize when copying data back to the GPU.

`iamin` and `iamax` were different in that regard because it returned a scalar on the CPU, so there's no point where we can synchronize.

2022-11-15 20:33 UTC, pengtu commented
> > Why does this `wait()`? It shouldn't, because that means these operations would synchronize the GPU. Instead, we only synchronize when copying data back to the GPU.
> > `iamin` and `iamax` were different in that regard because it returned a scalar on the CPU, so there's no point where we can synchronize.
> 
> The following test case fails spontaneously without the wait():
> 
> @test testf(axpy!, alpha[1], rand(T,m), rand(T,m))
> 
> Inside the "testf" function, it copies the GPU arrays back to the CPU. Your question indicates that a synchronization is already there. Would you point us to the synchronization code?
> 
> The oneMKL library call always return a SYCL event, do we need to hook it up into oneAPI.jl's dependency tracking module?
> 
> Another scenario is that the spontaneous failure is caused by running out of memory that you have recently fixed, unlikely but possible.

I can see the queue synchronization command at: 
https://github.com/JuliaGPU/oneAPI.jl/blob/master/src/array.jl#L322

Let's run ze_tracer to see the sequence of L0 calls when it failed.

2022-11-16 03:16 UTC, pengtu commented
> > > Why does this `wait()`? It shouldn't, because that means these operations would synchronize the GPU. Instead, we only synchronize when copying data back to the GPU.
> > > `iamin` and `iamax` were different in that regard because it returned a scalar on the CPU, so there's no point where we can synchronize.
> > 
> > 
> > The following test case fails spontaneously without the wait():
> > @test testf(axpy!, alpha[1], rand(T,m), rand(T,m))
> > Inside the "testf" function, it copies the GPU arrays back to the CPU. Your question indicates that a synchronization is already there. Would you point us to the synchronization code?
> > The oneMKL library call always return a SYCL event, do we need to hook it up into oneAPI.jl's dependency tracking module?
> > Another scenario is that the spontaneous failure is caused by running out of memory that you have recently fixed, unlikely but possible.
> 
> I can see the queue synchronization command at: https://github.com/JuliaGPU/oneAPI.jl/blob/master/src/array.jl#L322
> 
> Let's run ze_tracer to see the sequence of L0 calls when it failed.

One suspect is the SYCL runtime batching, which waits and grouping zeCommandList in batches for submission to reduce L0 submission overhead:

https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md

The environment variable SYCL_PI_LEVEL_ZERO_BATCH_SIZE=0 (default), letting the SYCL runtime to decide how many commands to wait before submitting them to the L0 queue.

When Julia issues zeSynchronizeCommandQueue, some of the oneMKL kernel could be waiting in the SYCL runtime to be batch-submitted.

2022-11-22 06:49 UTC, Sarbojit2019 commented
@kballeda, wait() is no longer needed as we have added force flush on every submission. Please update the PR with "__FORCE_MKL_FLUSH__(status)", you can find the use in latest source.

2022-11-22 10:46 UTC, kballeda commented
Updated with force_mkl_flush instead of wait()

2022-11-22 11:47 UTC, maleadt commented
LGTM. Needs a rebase though.

2022-11-22 15:15 UTC, merged